# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_VERSION = "2"

Vagrant.configure(VAGRANT_VERSION) do |config|

  # rethinkdb box
  config.vm.box = "afeldman/rethinkdb"

  # networkversion
  config.vm.network "private_network", ip: "10.19.17.12" 

  # portforwarding
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 29015, host: 29015
  config.vm.network :forwarded_port, guest: 28015, host: 28015

  # start the rethinkdb software
  config.vm.provision :shell, inline: "rethinkdb --bind all", run: 'always'

end
